package ui;

import persistencia.SesionSingleton;
import logica.RegistroManager;
import persistencia.Usuario;
import logica.ValidationResult;
import javax.swing.JOptionPane;
import logica.EnviadorCorreos;

  
public class Ajustes_Usuario extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Ajustes_Usuario.class.getName());
    public Usuario usuario = SesionSingleton.getInstance().getUsuarioLogueado();
    private EnviadorCorreos enviarCorreo = new EnviadorCorreos();


    /**
     * Creates new form Ajustes_Usuario
     */
    public Ajustes_Usuario() {
        initComponents();
        
        // ----- CASILLAS NO MODIFICABLES ----- //
        TextDepartamento.setText(usuario.getDepartamento());
        TextMunicipio.setText(usuario.getMunicipio());
        TextDependencia.setText(usuario.getDependencia());
        TextEmail.setText(usuario.getEmail());
        
        
        // ----- CASILLAS MODIFICABLES ----- //
        CasillaNombre.setText(usuario.getNombre());
        CasillaApellido.setText(usuario.getApellido());
        CasillaNumero1.setText(usuario.getTelefono());
        CasillaCargo.setText(usuario.getCargo());


        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TextVisualizacion = new javax.swing.JLabel();
        TextAcuerdo = new javax.swing.JLabel();
        ConfirmPassword = new javax.swing.JPasswordField();
        CasillaApellido = new javax.swing.JTextField();
        CasillaNombre = new javax.swing.JTextField();
        CasillaCargo = new javax.swing.JTextField();
        Password = new javax.swing.JPasswordField();
        Apellidos = new javax.swing.JLabel();
        Municipio = new javax.swing.JLabel();
        Nombre = new javax.swing.JLabel();
        Email = new javax.swing.JLabel();
        Numero = new javax.swing.JLabel();
        Cargo = new javax.swing.JLabel();
        Departamento = new javax.swing.JLabel();
        Confirmar_contraseña = new javax.swing.JLabel();
        Dependencia = new javax.swing.JLabel();
        Contraseña = new javax.swing.JLabel();
        JBotonSalir = new javax.swing.JButton();
        BotonGuardar = new javax.swing.JButton();
        BarraHorizontal = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        TextDepartamento = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        TextMunicipio = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        TextEmail = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        TextDependencia = new javax.swing.JLabel();
        CasillaNumero1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 251, 248));
        jPanel1.setForeground(new java.awt.Color(255, 251, 248));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TextVisualizacion.setFont(new java.awt.Font("Inter", 1, 30)); // NOI18N
        TextVisualizacion.setText("Ajustes de Usuario");
        jPanel1.add(TextVisualizacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        TextAcuerdo.setFont(new java.awt.Font("Inter", 1, 30)); // NOI18N
        TextAcuerdo.setForeground(new java.awt.Color(53, 91, 62));
        TextAcuerdo.setText("Modificar");
        jPanel1.add(TextAcuerdo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        ConfirmPassword.setFont(new java.awt.Font("Roboto Condensed", 2, 12)); // NOI18N
        ConfirmPassword.setForeground(new java.awt.Color(102, 102, 102));
        ConfirmPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ConfirmPasswordMousePressed(evt);
            }
        });
        ConfirmPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmPasswordActionPerformed(evt);
            }
        });
        jPanel1.add(ConfirmPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 490, 270, 40));

        CasillaApellido.setFont(new java.awt.Font("Roboto SemiCondensed", 0, 14)); // NOI18N
        CasillaApellido.setForeground(new java.awt.Color(102, 102, 102));
        CasillaApellido.setText("Ingrese su apellido");
        CasillaApellido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CasillaApellidoMousePressed(evt);
            }
        });
        CasillaApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CasillaApellidoActionPerformed(evt);
            }
        });
        jPanel1.add(CasillaApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, 270, 40));

        CasillaNombre.setFont(new java.awt.Font("Roboto SemiCondensed", 0, 14)); // NOI18N
        CasillaNombre.setForeground(new java.awt.Color(102, 102, 102));
        CasillaNombre.setText("Ingrese su nombre");
        CasillaNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CasillaNombreMousePressed(evt);
            }
        });
        CasillaNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CasillaNombreActionPerformed(evt);
            }
        });
        jPanel1.add(CasillaNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 270, 40));

        CasillaCargo.setFont(new java.awt.Font("Roboto SemiCondensed", 0, 14)); // NOI18N
        CasillaCargo.setForeground(new java.awt.Color(102, 102, 102));
        CasillaCargo.setText("Cargo");
        CasillaCargo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CasillaCargoMousePressed(evt);
            }
        });
        CasillaCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CasillaCargoActionPerformed(evt);
            }
        });
        jPanel1.add(CasillaCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 410, 270, 40));

        Password.setFont(new java.awt.Font("Roboto Condensed", 2, 12)); // NOI18N
        Password.setForeground(new java.awt.Color(102, 102, 102));
        Password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PasswordMousePressed(evt);
            }
        });
        Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordActionPerformed(evt);
            }
        });
        jPanel1.add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 270, 40));

        Apellidos.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        Apellidos.setText("Apellidos");
        jPanel1.add(Apellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, -1, 20));

        Municipio.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        Municipio.setText("Municipio");
        jPanel1.add(Municipio, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, -1, 30));

        Nombre.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        Nombre.setText("Nombre");
        jPanel1.add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, 20));

        Email.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        Email.setText("Email");
        jPanel1.add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, 20));

        Numero.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        Numero.setText("Numero");
        jPanel1.add(Numero, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, -1, 20));

        Cargo.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        Cargo.setText("Cargo");
        jPanel1.add(Cargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 380, -1, 30));

        Departamento.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        Departamento.setText("Departamento");
        jPanel1.add(Departamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, 30));

        Confirmar_contraseña.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        Confirmar_contraseña.setText("Confirmar Contraseña");
        jPanel1.add(Confirmar_contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 460, -1, 30));

        Dependencia.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        Dependencia.setText("Dependencia Perteneciente");
        jPanel1.add(Dependencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, -1, 30));

        Contraseña.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        Contraseña.setText("Nuevo Contraseña");
        jPanel1.add(Contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, -1, 30));

        JBotonSalir.setBackground(new java.awt.Color(255, 204, 204));
        JBotonSalir.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        JBotonSalir.setForeground(new java.awt.Color(204, 0, 51));
        JBotonSalir.setText("Salir");
        JBotonSalir.setBorderPainted(false);
        JBotonSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JBotonSalirMouseClicked(evt);
            }
        });
        jPanel1.add(JBotonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 560, 110, 50));

        BotonGuardar.setBackground(new java.awt.Color(204, 204, 255));
        BotonGuardar.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        BotonGuardar.setForeground(new java.awt.Color(0, 0, 153));
        BotonGuardar.setText("Guardar");
        BotonGuardar.setActionCommand("GUARDAR");
        BotonGuardar.setBorderPainted(false);
        BotonGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonGuardarMouseClicked(evt);
            }
        });
        jPanel1.add(BotonGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 560, 110, 50));

        BarraHorizontal.setBackground(new java.awt.Color(219, 219, 219));

        javax.swing.GroupLayout BarraHorizontalLayout = new javax.swing.GroupLayout(BarraHorizontal);
        BarraHorizontal.setLayout(BarraHorizontalLayout);
        BarraHorizontalLayout.setHorizontalGroup(
            BarraHorizontalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        BarraHorizontalLayout.setVerticalGroup(
            BarraHorizontalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(BarraHorizontal, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 560, 4));

        TextDepartamento.setFont(new java.awt.Font("Roboto Condensed", 1, 14)); // NOI18N
        TextDepartamento.setText("Departamento de usuario");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(TextDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(101, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TextDepartamento, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 267, 36));

        TextMunicipio.setFont(new java.awt.Font("Roboto Condensed", 1, 14)); // NOI18N
        TextMunicipio.setText("Municipio de usuario");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(TextMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(101, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TextMunicipio, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 330, 267, 36));

        TextEmail.setFont(new java.awt.Font("Roboto Condensed", 1, 14)); // NOI18N
        TextEmail.setText("Email de usuario");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(TextEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(101, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TextEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 267, 36));

        TextDependencia.setFont(new java.awt.Font("Roboto Condensed", 1, 14)); // NOI18N
        TextDependencia.setText("Dependencia de usuario");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(TextDependencia, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(101, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TextDependencia, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, -1, -1));

        CasillaNumero1.setFont(new java.awt.Font("Roboto SemiCondensed", 0, 14)); // NOI18N
        CasillaNumero1.setForeground(new java.awt.Color(102, 102, 102));
        CasillaNumero1.setText("+57 --- ----- ----");
        CasillaNumero1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CasillaNumero1MousePressed(evt);
            }
        });
        CasillaNumero1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CasillaNumero1ActionPerformed(evt);
            }
        });
        jPanel1.add(CasillaNumero1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 250, 270, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 643, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 634, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ConfirmPasswordMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConfirmPasswordMousePressed

    }//GEN-LAST:event_ConfirmPasswordMousePressed

    private void ConfirmPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConfirmPasswordActionPerformed

    private void CasillaApellidoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CasillaApellidoMousePressed

    }//GEN-LAST:event_CasillaApellidoMousePressed

    private void CasillaApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CasillaApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CasillaApellidoActionPerformed

    private void CasillaNombreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CasillaNombreMousePressed

    }//GEN-LAST:event_CasillaNombreMousePressed

    private void CasillaNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CasillaNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CasillaNombreActionPerformed

    private void PasswordMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PasswordMousePressed

    }//GEN-LAST:event_PasswordMousePressed

    private void PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordActionPerformed

    private void JBotonSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBotonSalirMouseClicked
        this.dispose();
        Gestor_De_Documentos gestorDocumentos = new Gestor_De_Documentos("", 0L);
        gestorDocumentos.setLocationRelativeTo(null);
        gestorDocumentos.setVisible(true);
    }//GEN-LAST:event_JBotonSalirMouseClicked

    private void CasillaCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CasillaCargoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CasillaCargoActionPerformed

    private void CasillaCargoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CasillaCargoMousePressed

    }//GEN-LAST:event_CasillaCargoMousePressed

    private void CasillaNumero1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CasillaNumero1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_CasillaNumero1MousePressed

    private void CasillaNumero1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CasillaNumero1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CasillaNumero1ActionPerformed

    private void BotonGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonGuardarMouseClicked
        String email = usuario.getEmail(); // usuario logueado

        String nuevoNombre   = CasillaNombre.getText().trim();
        String nuevoApellido = CasillaApellido.getText().trim();
        String nuevoNumero   = CasillaNumero1.getText().trim();
        String nuevoCargo    = CasillaCargo.getText().trim();

        String nuevaContrasena          = new String(Password.getPassword()).trim();
        String confirmarNuevaContrasena = new String(ConfirmPassword.getPassword()).trim();

        RegistroManager manager = new RegistroManager("usuarios.csv");
        ValidationResult resultado = manager.modificarUsuario(
                email,
                nuevoNombre,
                nuevoApellido,
                nuevoNumero,
                nuevoCargo,
                nuevaContrasena,
                confirmarNuevaContrasena
        );

        if (resultado.isSuccess()) {
            // Actualizar también el objeto en sesión
            usuario.setNombre(nuevoNombre);
            usuario.setApellido(nuevoApellido);
            usuario.setTelefono(nuevoNumero);
            usuario.setCargo(nuevoCargo);

            JOptionPane.showMessageDialog(this,
                    "Datos actualizados correctamente.",
                    "Éxito",
                    JOptionPane.INFORMATION_MESSAGE);
            
            // ====== CORREO DE NOTIFICACIÓN AL PROPIO USUARIO ======
            new Thread(() -> {
                try {
                    String asunto = "SwiftFold: actualización de datos de tu cuenta";

                    StringBuilder cuerpo = new StringBuilder();
                    cuerpo.append("Hola ").append(usuario.getNombreCompleto()).append(",\n\n")
                          .append("Te informamos que se realizó una actualización de los datos\n")
                          .append("en el sistema de gestión documental SwiftFold.\n\n")
                          .append("Datos actuales registrados:\n")
                          .append("• Nombre completo: ").append(nuevoNombre).append(" ").append(nuevoApellido).append("\n")
                          .append("• Correo electrónico: ").append(usuario.getEmail()).append("\n")
                          .append("• Número de contacto: ").append(nuevoNumero).append("\n")
                          .append("• Cargo: ").append(nuevoCargo).append("\n")
                          .append("• Dependencia: ").append(usuario.getDependencia()).append("\n")
                          .append("• Municipio / Departamento: ")
                             .append(usuario.getMunicipio()).append(" - ").append(usuario.getDepartamento()).append("\n\n");

                    // Mencionar si se cambió la contraseña (campo no vacío)
                    if (!nuevaContrasena.isEmpty()) {
                        cuerpo.append("Además, se registró un cambio de contraseña asociado a tu cuenta.\n\n");
                    }

                    cuerpo.append("Si no reconoces esta acción, comunícate con el administrador del sistema.\n\n")
                          .append("Atentamente,\n")
                          .append("SwiftFold – Sistema de Gestión Documental");

                    enviarCorreo.nuevoUsuarioEliminarModificar(cuerpo.toString(), asunto);

                } catch (Exception exCorreo) {
                    System.err.println("No se pudo enviar el correo de notificación: " + exCorreo.getMessage());
                }
            }).start();
            // ======================================================
            
            
            this.dispose();
            Gestor_De_Documentos gestorDocumentos = new Gestor_De_Documentos("", 0L);
            gestorDocumentos.setLocationRelativeTo(null);
            gestorDocumentos.setVisible(true);

        } else {
            StringBuilder sb = new StringBuilder();
            for (String msg : resultado.getMessages()) {
                sb.append(msg).append("\n");
            }
            JOptionPane.showMessageDialog(this,
                    sb.toString(),
                    "Error al actualizar",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BotonGuardarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Ajustes_Usuario().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Apellidos;
    private javax.swing.JPanel BarraHorizontal;
    private javax.swing.JButton BotonGuardar;
    private javax.swing.JLabel Cargo;
    private javax.swing.JTextField CasillaApellido;
    private javax.swing.JTextField CasillaCargo;
    private javax.swing.JTextField CasillaNombre;
    private javax.swing.JTextField CasillaNumero1;
    private javax.swing.JPasswordField ConfirmPassword;
    private javax.swing.JLabel Confirmar_contraseña;
    private javax.swing.JLabel Contraseña;
    private javax.swing.JLabel Departamento;
    private javax.swing.JLabel Dependencia;
    private javax.swing.JLabel Email;
    private javax.swing.JButton JBotonSalir;
    private javax.swing.JLabel Municipio;
    private javax.swing.JLabel Nombre;
    private javax.swing.JLabel Numero;
    private javax.swing.JPasswordField Password;
    private javax.swing.JLabel TextAcuerdo;
    private javax.swing.JLabel TextDepartamento;
    private javax.swing.JLabel TextDependencia;
    private javax.swing.JLabel TextEmail;
    private javax.swing.JLabel TextMunicipio;
    private javax.swing.JLabel TextVisualizacion;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    // End of variables declaration//GEN-END:variables
}
