/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import java.awt.Color;

/**
 *
 * @author Juan Pablo
 */
public class Ajustes_Usuario extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Ajustes_Usuario.class.getName());

    /**
     * Creates new form Ajustes_Usuario
     */
    public Ajustes_Usuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TextVisualizacion = new javax.swing.JLabel();
        TextAcuerdo = new javax.swing.JLabel();
        CasillaCargo = new javax.swing.JTextField();
        SelectMunicipio = new javax.swing.JComboBox<>();
        SelectDependencia = new javax.swing.JComboBox<>();
        ConfirmPassword = new javax.swing.JPasswordField();
        CasillaApellido = new javax.swing.JTextField();
        CasillaNombre = new javax.swing.JTextField();
        CasillaEmail = new javax.swing.JTextField();
        SelectDepart = new javax.swing.JComboBox<>();
        CasillaNumero = new javax.swing.JTextField();
        Password = new javax.swing.JPasswordField();
        Apellidos = new javax.swing.JLabel();
        Municipio = new javax.swing.JLabel();
        Nombre = new javax.swing.JLabel();
        Email = new javax.swing.JLabel();
        Numero = new javax.swing.JLabel();
        Cargo = new javax.swing.JLabel();
        Departamento = new javax.swing.JLabel();
        Confirmar_contraseña = new javax.swing.JLabel();
        Dependencia = new javax.swing.JLabel();
        Contraseña = new javax.swing.JLabel();
        JBotonSalir = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        BarraHorizontal = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 251, 248));
        jPanel1.setForeground(new java.awt.Color(255, 251, 248));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TextVisualizacion.setFont(new java.awt.Font("Inter", 1, 30)); // NOI18N
        TextVisualizacion.setText("Ajustes de Usuario");
        jPanel1.add(TextVisualizacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        TextAcuerdo.setFont(new java.awt.Font("Inter", 1, 30)); // NOI18N
        TextAcuerdo.setForeground(new java.awt.Color(53, 91, 62));
        TextAcuerdo.setText("Modificar");
        jPanel1.add(TextAcuerdo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        CasillaCargo.setFont(new java.awt.Font("Roboto SemiCondensed", 0, 14)); // NOI18N
        CasillaCargo.setForeground(new java.awt.Color(102, 102, 102));
        CasillaCargo.setText("Ingrese el cargo");
        CasillaCargo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CasillaCargoMousePressed(evt);
            }
        });
        CasillaCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CasillaCargoActionPerformed(evt);
            }
        });
        jPanel1.add(CasillaCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 410, 270, 40));

        SelectMunicipio.setFont(new java.awt.Font("Roboto SemiCondensed", 0, 14)); // NOI18N
        SelectMunicipio.setForeground(new java.awt.Color(102, 102, 102));
        SelectMunicipio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectMunicipioActionPerformed(evt);
            }
        });
        jPanel1.add(SelectMunicipio, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 330, 270, 40));

        SelectDependencia.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        SelectDependencia.setForeground(new java.awt.Color(102, 102, 102));
        SelectDependencia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Secretaría General", "Secretaría de Gobierno", "Secretaría de Hacienda", "Secretaría de Planeación", "Secretaría de Salud", "Secretaría de Educación", "Secretaría de Infraestructura", "Secretaría de Desarrollo Social", "Secretaría de Desarrollo Económico", "Secretaría de Agricultura", "Secretaría de Ambiente", "Secretaría de Tránsito y Transporte", "Secretaría de Cultura y Turismo", "Secretaría de Deporte y Recreación", "Oficina Jurídica", "Oficina de Control Interno", "Oficina TIC / Sistemas", "Gestión Documental / Archivo", "Oficina de Prensa y Comunicaciones", "Gestión del Riesgo", "Inspección de Policía", "Comisaría de Familia", "Personería (si aplica)" }));
        SelectDependencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectDependenciaActionPerformed(evt);
            }
        });
        jPanel1.add(SelectDependencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 270, 40));

        ConfirmPassword.setFont(new java.awt.Font("Roboto Condensed", 2, 12)); // NOI18N
        ConfirmPassword.setForeground(new java.awt.Color(102, 102, 102));
        ConfirmPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ConfirmPasswordMousePressed(evt);
            }
        });
        ConfirmPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmPasswordActionPerformed(evt);
            }
        });
        jPanel1.add(ConfirmPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 490, 270, 40));

        CasillaApellido.setFont(new java.awt.Font("Roboto SemiCondensed", 0, 14)); // NOI18N
        CasillaApellido.setForeground(new java.awt.Color(102, 102, 102));
        CasillaApellido.setText("Ingrese su apellido");
        CasillaApellido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CasillaApellidoMousePressed(evt);
            }
        });
        CasillaApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CasillaApellidoActionPerformed(evt);
            }
        });
        jPanel1.add(CasillaApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, 270, 40));

        CasillaNombre.setFont(new java.awt.Font("Roboto SemiCondensed", 0, 14)); // NOI18N
        CasillaNombre.setForeground(new java.awt.Color(102, 102, 102));
        CasillaNombre.setText("Ingrese su nombre");
        CasillaNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CasillaNombreMousePressed(evt);
            }
        });
        CasillaNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CasillaNombreActionPerformed(evt);
            }
        });
        jPanel1.add(CasillaNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 270, 40));

        CasillaEmail.setFont(new java.awt.Font("Roboto SemiCondensed", 0, 14)); // NOI18N
        CasillaEmail.setForeground(new java.awt.Color(102, 102, 102));
        CasillaEmail.setText("correo@gmail.com");
        CasillaEmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CasillaEmailMousePressed(evt);
            }
        });
        CasillaEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CasillaEmailActionPerformed(evt);
            }
        });
        jPanel1.add(CasillaEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 270, 40));

        SelectDepart.setFont(new java.awt.Font("Roboto SemiCondensed", 0, 14)); // NOI18N
        SelectDepart.setForeground(new java.awt.Color(102, 102, 102));
        SelectDepart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectDepartActionPerformed(evt);
            }
        });
        jPanel1.add(SelectDepart, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 270, 40));

        CasillaNumero.setFont(new java.awt.Font("Roboto SemiCondensed", 0, 14)); // NOI18N
        CasillaNumero.setForeground(new java.awt.Color(102, 102, 102));
        CasillaNumero.setText("+57 --- ----- ----");
        CasillaNumero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CasillaNumeroMousePressed(evt);
            }
        });
        CasillaNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CasillaNumeroActionPerformed(evt);
            }
        });
        jPanel1.add(CasillaNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 250, 270, 40));

        Password.setFont(new java.awt.Font("Roboto Condensed", 2, 12)); // NOI18N
        Password.setForeground(new java.awt.Color(102, 102, 102));
        Password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PasswordMousePressed(evt);
            }
        });
        Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordActionPerformed(evt);
            }
        });
        jPanel1.add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 270, 40));

        Apellidos.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        Apellidos.setText("Apellidos");
        jPanel1.add(Apellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, -1, 20));

        Municipio.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        Municipio.setText("Municipio");
        jPanel1.add(Municipio, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, -1, 30));

        Nombre.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        Nombre.setText("Nombre");
        jPanel1.add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, 20));

        Email.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        Email.setText("Email");
        jPanel1.add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, 20));

        Numero.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        Numero.setText("Numero");
        jPanel1.add(Numero, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, -1, 20));

        Cargo.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        Cargo.setText("Cargo");
        jPanel1.add(Cargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 380, -1, 30));

        Departamento.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        Departamento.setText("Departamento");
        jPanel1.add(Departamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, 30));

        Confirmar_contraseña.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        Confirmar_contraseña.setText("Confirmar Contraseña");
        jPanel1.add(Confirmar_contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 460, -1, 30));

        Dependencia.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        Dependencia.setText("Dependencia Perteneciente");
        jPanel1.add(Dependencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, -1, 30));

        Contraseña.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        Contraseña.setText("Contraseña");
        jPanel1.add(Contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, -1, 30));

        JBotonSalir.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        JBotonSalir.setText("Salir");
        JBotonSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JBotonSalirMouseClicked(evt);
            }
        });
        jPanel1.add(JBotonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 560, 110, 50));

        jButton3.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jButton3.setText("Guardar");
        jButton3.setActionCommand("GUARDAR");
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 560, 110, 50));

        BarraHorizontal.setBackground(new java.awt.Color(219, 219, 219));

        javax.swing.GroupLayout BarraHorizontalLayout = new javax.swing.GroupLayout(BarraHorizontal);
        BarraHorizontal.setLayout(BarraHorizontalLayout);
        BarraHorizontalLayout.setHorizontalGroup(
            BarraHorizontalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        BarraHorizontalLayout.setVerticalGroup(
            BarraHorizontalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(BarraHorizontal, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 560, 4));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 643, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 634, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CasillaCargoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CasillaCargoMousePressed
        if (CasillaCargo.getText().equals("Ingrese el cargo")) {
            CasillaCargo.setText("");
            CasillaCargo.setForeground(Color.black);
        }
        if (CasillaNombre.getText().isEmpty()) {
            CasillaNombre.setText("Ingrese su nombre");
            CasillaNombre.setForeground(Color.gray);
        }
        if (CasillaApellido.getText().isEmpty()) {
            CasillaApellido.setText("Ingrese su apellido");
            CasillaApellido.setForeground(Color.gray);
        }
        if (CasillaEmail.getText().isEmpty()) {
            CasillaEmail.setText("correo@gmail.com");
            CasillaEmail.setForeground(Color.gray);
        }
        if (CasillaNumero.getText().isEmpty()) {
            CasillaNumero.setText("+57 --- ----- ----");
            CasillaNumero.setForeground(Color.gray);
        }
        if (Password.getPassword().length == 0) {
            Password.setText("********");
            Password.setForeground(Color.gray);
            Password.setEchoChar((char)0);
        }
        if (ConfirmPassword.getPassword().length == 0) {
            ConfirmPassword.setText("********");
            ConfirmPassword.setForeground(Color.gray);
            ConfirmPassword.setEchoChar((char)0);
        }
    }//GEN-LAST:event_CasillaCargoMousePressed

    private void CasillaCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CasillaCargoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CasillaCargoActionPerformed

    private void SelectMunicipioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectMunicipioActionPerformed

    }//GEN-LAST:event_SelectMunicipioActionPerformed

    private void SelectDependenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectDependenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SelectDependenciaActionPerformed

    private void ConfirmPasswordMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConfirmPasswordMousePressed
        String pwd = new String(ConfirmPassword.getPassword());
        if (pwd.equals("********")) {
            ConfirmPassword.setText("");
            ConfirmPassword.setForeground(Color.black);
            ConfirmPassword.setEchoChar('\u2022');
        }
        if (CasillaNombre.getText().isEmpty()) {
            CasillaNombre.setText("Ingrese su nombre");
            CasillaNombre.setForeground(Color.gray);
        }
        if (CasillaApellido.getText().isEmpty()) {
            CasillaApellido.setText("Ingrese su apellido");
            CasillaApellido.setForeground(Color.gray);
        }
        if (CasillaEmail.getText().isEmpty()) {
            CasillaEmail.setText("correo@gmail.com");
            CasillaEmail.setForeground(Color.gray);
        }
        if (CasillaNumero.getText().isEmpty()) {
            CasillaNumero.setText("+57 --- ----- ----");
            CasillaNumero.setForeground(Color.gray);
        }
        if (CasillaCargo.getText().isEmpty()) {
            CasillaCargo.setText("Ingrese el cargo");
            CasillaCargo.setForeground(Color.gray);
        }
        if (Password.getPassword().length == 0) {
            Password.setText("********");
            Password.setForeground(Color.gray);
            Password.setEchoChar((char)0);
        }
    }//GEN-LAST:event_ConfirmPasswordMousePressed

    private void ConfirmPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConfirmPasswordActionPerformed

    private void CasillaApellidoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CasillaApellidoMousePressed
        if (CasillaApellido.getText().equals("Ingrese su apellido")) {
            CasillaApellido.setText("");
            CasillaApellido.setForeground(Color.black);
        }
        if (CasillaNombre.getText().isEmpty()) {
            CasillaNombre.setText("Ingrese su nombre");
            CasillaNombre.setForeground(Color.gray);
        }
        if (CasillaEmail.getText().isEmpty()) {
            CasillaEmail.setText("correo@gmail.com");
            CasillaEmail.setForeground(Color.gray);
        }
        if (CasillaNumero.getText().isEmpty()) {
            CasillaNumero.setText("+57 --- ----- ----");
            CasillaNumero.setForeground(Color.gray);
        }
        if (CasillaCargo.getText().isEmpty()) {
            CasillaCargo.setText("Ingrese el cargo");
            CasillaCargo.setForeground(Color.gray);
        }
        if (Password.getPassword().length == 0) {
            Password.setText("********");
            Password.setForeground(Color.gray);
            Password.setEchoChar((char)0);
        }
        if (ConfirmPassword.getPassword().length == 0) {
            ConfirmPassword.setText("********");
            ConfirmPassword.setForeground(Color.gray);
            ConfirmPassword.setEchoChar((char)0);
        }
    }//GEN-LAST:event_CasillaApellidoMousePressed

    private void CasillaApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CasillaApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CasillaApellidoActionPerformed

    private void CasillaNombreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CasillaNombreMousePressed
        if (CasillaNombre.getText().equals("Ingrese su nombre")) {
            CasillaNombre.setText("");
            CasillaNombre.setForeground(Color.black);
        }
        // Restaurar placeholders en los demás si están vacíos
        if (CasillaApellido.getText().isEmpty()) {
            CasillaApellido.setText("Ingrese su apellido");
            CasillaApellido.setForeground(Color.gray);
        }
        if (CasillaEmail.getText().isEmpty()) {
            CasillaEmail.setText("correo@gmail.com");
            CasillaEmail.setForeground(Color.gray);
        }
        if (CasillaNumero.getText().isEmpty()) {
            CasillaNumero.setText("+57 --- ----- ----");
            CasillaNumero.setForeground(Color.gray);
        }
        if (CasillaCargo.getText().isEmpty()) {
            CasillaCargo.setText("Ingrese el cargo");
            CasillaCargo.setForeground(Color.gray);
        }
        if (Password.getPassword().length == 0) {
            Password.setText("********");
            Password.setForeground(Color.gray);
            Password.setEchoChar((char)0);
        }
        if (ConfirmPassword.getPassword().length == 0) {
            ConfirmPassword.setText("********");
            ConfirmPassword.setForeground(Color.gray);
            ConfirmPassword.setEchoChar((char)0);
        }
    }//GEN-LAST:event_CasillaNombreMousePressed

    private void CasillaNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CasillaNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CasillaNombreActionPerformed

    private void CasillaEmailMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CasillaEmailMousePressed
        if (CasillaEmail.getText().equals("correo@gmail.com")) {
            CasillaEmail.setText("");
            CasillaEmail.setForeground(Color.black);
        }
        if (CasillaNombre.getText().isEmpty()) {
            CasillaNombre.setText("Ingrese su nombre");
            CasillaNombre.setForeground(Color.gray);
        }
        if (CasillaApellido.getText().isEmpty()) {
            CasillaApellido.setText("Ingrese su apellido");
            CasillaApellido.setForeground(Color.gray);
        }
        if (CasillaNumero.getText().isEmpty()) {
            CasillaNumero.setText("+57 --- ----- ----");
            CasillaNumero.setForeground(Color.gray);
        }
        if (CasillaCargo.getText().isEmpty()) {
            CasillaCargo.setText("Ingrese el cargo");
            CasillaCargo.setForeground(Color.gray);
        }
        if (Password.getPassword().length == 0) {
            Password.setText("********");
            Password.setForeground(Color.gray);
            Password.setEchoChar((char)0);
        }
        if (ConfirmPassword.getPassword().length == 0) {
            ConfirmPassword.setText("********");
            ConfirmPassword.setForeground(Color.gray);
            ConfirmPassword.setEchoChar((char)0);
        }
    }//GEN-LAST:event_CasillaEmailMousePressed

    private void CasillaEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CasillaEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CasillaEmailActionPerformed

    private void SelectDepartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectDepartActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SelectDepartActionPerformed

    private void CasillaNumeroMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CasillaNumeroMousePressed
        if (CasillaNumero.getText().equals("+57 --- ----- ----")) {
            CasillaNumero.setText("");
            CasillaNumero.setForeground(Color.black);
        }
        if (CasillaNombre.getText().isEmpty()) {
            CasillaNombre.setText("Ingrese su nombre");
            CasillaNombre.setForeground(Color.gray);
        }
        if (CasillaApellido.getText().isEmpty()) {
            CasillaApellido.setText("Ingrese su apellido");
            CasillaApellido.setForeground(Color.gray);
        }
        if (CasillaEmail.getText().isEmpty()) {
            CasillaEmail.setText("correo@gmail.com");
            CasillaEmail.setForeground(Color.gray);
        }
        if (CasillaCargo.getText().isEmpty()) {
            CasillaCargo.setText("Ingrese el cargo");
            CasillaCargo.setForeground(Color.gray);
        }
        if (Password.getPassword().length == 0) {
            Password.setText("********");
            Password.setForeground(Color.gray);
            Password.setEchoChar((char)0);
        }
        if (ConfirmPassword.getPassword().length == 0) {
            ConfirmPassword.setText("********");
            ConfirmPassword.setForeground(Color.gray);
            ConfirmPassword.setEchoChar((char)0);
        }
    }//GEN-LAST:event_CasillaNumeroMousePressed

    private void CasillaNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CasillaNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CasillaNumeroActionPerformed

    private void PasswordMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PasswordMousePressed
        String pwd = new String(Password.getPassword());
        if (pwd.equals("********")) {
            Password.setText("");
            Password.setForeground(Color.black);
            Password.setEchoChar('\u2022'); // vuelve a ocultar
        }
        // Placeholders en los demás
        if (CasillaNombre.getText().isEmpty()) {
            CasillaNombre.setText("Ingrese su nombre");
            CasillaNombre.setForeground(Color.gray);
        }
        if (CasillaApellido.getText().isEmpty()) {
            CasillaApellido.setText("Ingrese su apellido");
            CasillaApellido.setForeground(Color.gray);
        }
        if (CasillaEmail.getText().isEmpty()) {
            CasillaEmail.setText("correo@gmail.com");
            CasillaEmail.setForeground(Color.gray);
        }
        if (CasillaNumero.getText().isEmpty()) {
            CasillaNumero.setText("+57 --- ----- ----");
            CasillaNumero.setForeground(Color.gray);
        }
        if (CasillaCargo.getText().isEmpty()) {
            CasillaCargo.setText("Ingrese el cargo");
            CasillaCargo.setForeground(Color.gray);
        }
        if (ConfirmPassword.getPassword().length == 0) {
            ConfirmPassword.setText("********");
            ConfirmPassword.setForeground(Color.gray);
            ConfirmPassword.setEchoChar((char)0);
        }
    }//GEN-LAST:event_PasswordMousePressed

    private void PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordActionPerformed

    private void JBotonSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBotonSalirMouseClicked
        this.dispose();
        Gesto_De_Usuarios gestorUsuarios = new Gesto_De_Usuarios();
        gestorUsuarios.setLocationRelativeTo(null);
        gestorUsuarios.setVisible(true);
    }//GEN-LAST:event_JBotonSalirMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Ajustes_Usuario().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Apellidos;
    private javax.swing.JPanel BarraHorizontal;
    private javax.swing.JLabel Cargo;
    private javax.swing.JTextField CasillaApellido;
    private javax.swing.JTextField CasillaCargo;
    private javax.swing.JTextField CasillaEmail;
    private javax.swing.JTextField CasillaNombre;
    private javax.swing.JTextField CasillaNumero;
    private javax.swing.JPasswordField ConfirmPassword;
    private javax.swing.JLabel Confirmar_contraseña;
    private javax.swing.JLabel Contraseña;
    private javax.swing.JLabel Departamento;
    private javax.swing.JLabel Dependencia;
    private javax.swing.JLabel Email;
    private javax.swing.JButton JBotonSalir;
    private javax.swing.JLabel Municipio;
    private javax.swing.JLabel Nombre;
    private javax.swing.JLabel Numero;
    private javax.swing.JPasswordField Password;
    private javax.swing.JComboBox<String> SelectDepart;
    private javax.swing.JComboBox<String> SelectDependencia;
    private javax.swing.JComboBox<String> SelectMunicipio;
    private javax.swing.JLabel TextAcuerdo;
    private javax.swing.JLabel TextVisualizacion;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
