package ui;

import javax.swing.JOptionPane;
import logica.CategoriaDao;


public class Eliminar_Categoria extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Eliminar_Categoria.class.getName());

    /**
     * Creates new form Eliminar_Categoria
     */
    public Eliminar_Categoria() {
        initComponents();
        cargarInformacion();
    }
     
    private void cargarInformacion() {
            
        JComboBoxCategorias.removeAllItems();
        JComboBoxCategorias.addItem("Seleccione una categoría…");
        
        // Me lee la bases de datos y aparte los agrega al combobox
        try {
            for (String nombre : new CategoriaDao().listarNombres()) {
                JComboBoxCategorias.addItem(nombre);
            }
        } catch (Exception ex) {
            System.err.println("No se pudieron cargar categorías: " + ex.getMessage());
        }

        JComboBoxCategorias.setSelectedIndex(0);
    }
    
    private void recargarCategorias() {
        CategoriaDao dao = new CategoriaDao();
        java.util.List<String> nombres = dao.listarNombres();

        JComboBoxCategorias.removeAllItems();
        for (String n : nombres) {
            JComboBoxCategorias.addItem(n);
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TextVisualizacion = new javax.swing.JLabel();
        TextCambiable = new javax.swing.JLabel();
        BarraHorizontal = new javax.swing.JPanel();
        JBotonSalir = new javax.swing.JButton();
        JBotonGuardar = new javax.swing.JButton();
        JComboBoxCategorias = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTextDescripcion = new javax.swing.JTextArea();
        JBotonEliminar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 251, 248));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TextVisualizacion.setFont(new java.awt.Font("Inter", 1, 30)); // NOI18N
        TextVisualizacion.setText("Modificar Categoria");
        jPanel1.add(TextVisualizacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        TextCambiable.setFont(new java.awt.Font("Inter", 1, 30)); // NOI18N
        TextCambiable.setForeground(new java.awt.Color(53, 91, 62));
        TextCambiable.setText("Eliminar Categoria");
        jPanel1.add(TextCambiable, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        BarraHorizontal.setBackground(new java.awt.Color(219, 219, 219));

        javax.swing.GroupLayout BarraHorizontalLayout = new javax.swing.GroupLayout(BarraHorizontal);
        BarraHorizontal.setLayout(BarraHorizontalLayout);
        BarraHorizontalLayout.setHorizontalGroup(
            BarraHorizontalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        BarraHorizontalLayout.setVerticalGroup(
            BarraHorizontalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(BarraHorizontal, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 480, 4));

        JBotonSalir.setBackground(new java.awt.Color(204, 255, 204));
        JBotonSalir.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        JBotonSalir.setForeground(new java.awt.Color(0, 51, 51));
        JBotonSalir.setText("Salir");
        JBotonSalir.setBorderPainted(false);
        JBotonSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JBotonSalirMouseClicked(evt);
            }
        });
        JBotonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBotonSalirActionPerformed(evt);
            }
        });
        jPanel1.add(JBotonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 400, 110, 50));

        JBotonGuardar.setBackground(new java.awt.Color(204, 204, 255));
        JBotonGuardar.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        JBotonGuardar.setForeground(new java.awt.Color(0, 0, 153));
        JBotonGuardar.setText("Guardar");
        JBotonGuardar.setActionCommand("GUARDAR");
        JBotonGuardar.setBorderPainted(false);
        JBotonGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JBotonGuardarMouseClicked(evt);
            }
        });
        JBotonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBotonGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(JBotonGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 400, 110, 50));

        JComboBoxCategorias.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        JComboBoxCategorias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        JComboBoxCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JComboBoxCategoriasActionPerformed(evt);
            }
        });
        jPanel1.add(JComboBoxCategorias, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 480, 40));

        jLabel1.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jLabel1.setText("Elije la categoria");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 120, -1));

        jLabel2.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jLabel2.setText("Descripcion de la Categoria:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        JTextDescripcion.setColumns(20);
        JTextDescripcion.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        JTextDescripcion.setRows(5);
        jScrollPane1.setViewportView(JTextDescripcion);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 480, -1));

        JBotonEliminar1.setBackground(new java.awt.Color(255, 204, 204));
        JBotonEliminar1.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        JBotonEliminar1.setForeground(new java.awt.Color(204, 0, 51));
        JBotonEliminar1.setText("Eliminar");
        JBotonEliminar1.setActionCommand("GUARDAR");
        JBotonEliminar1.setBorderPainted(false);
        JBotonEliminar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JBotonEliminar1MouseClicked(evt);
            }
        });
        JBotonEliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBotonEliminar1ActionPerformed(evt);
            }
        });
        jPanel1.add(JBotonEliminar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 400, 110, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBotonSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBotonSalirMouseClicked
        this.dispose();

        Gestor_De_Documentos ventanaGestorDocumentos = new Gestor_De_Documentos("", 0L);
        ventanaGestorDocumentos.setLocationRelativeTo(null);
        ventanaGestorDocumentos.setVisible(true);
    }//GEN-LAST:event_JBotonSalirMouseClicked

    private void JBotonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBotonSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBotonSalirActionPerformed

    private void JBotonGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBotonGuardarMouseClicked

    }//GEN-LAST:event_JBotonGuardarMouseClicked

    private void JBotonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBotonGuardarActionPerformed
        String nombre = (String) JComboBoxCategorias.getSelectedItem();
        String nuevaDescripcion = JTextDescripcion.getText().trim();

        if (nombre == null || nombre.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Debe seleccionar una categoría.",
                    "Aviso",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        CategoriaDao dao = new CategoriaDao();
        boolean ok = dao.modificarCategoria(nombre, nuevaDescripcion);

        if (ok) {
            JOptionPane.showMessageDialog(this,
                    "Descripción actualizada correctamente.",
                    "Éxito",
                    JOptionPane.INFORMATION_MESSAGE);
            
        } else {
            JOptionPane.showMessageDialog(this,
                    "No se pudo actualizar la categoría.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_JBotonGuardarActionPerformed

    private void JBotonEliminar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBotonEliminar1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_JBotonEliminar1MouseClicked

    private void JBotonEliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBotonEliminar1ActionPerformed
        String nombre = (String) JComboBoxCategorias.getSelectedItem();
        
        if (nombre.equalsIgnoreCase("Sin categoría")) {
            JOptionPane.showMessageDialog(this,
                "La categoría 'Sin categoría' no puede eliminarse.",
                "Acción no permitida",
                JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (nombre == null || nombre.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Debe seleccionar una categoría.",
                    "Aviso",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        int opcion = JOptionPane.showConfirmDialog(
                this,
                "¿Seguro que desea eliminar la categoría '" + nombre + "'?",
                "Confirmar eliminación",
                JOptionPane.YES_NO_OPTION
        );

        if (opcion != JOptionPane.YES_OPTION) return;

        CategoriaDao dao = new CategoriaDao();
        boolean eliminada = dao.eliminarCategoria(nombre);

        if (eliminada) {
            JOptionPane.showMessageDialog(this,
                    "Categoría eliminada correctamente.",
                    "Éxito",
                    JOptionPane.INFORMATION_MESSAGE);

            // Recargar combo de categorías
            recargarCategorias();
            JTextDescripcion.setText("");

        } else {
            JOptionPane.showMessageDialog(this,
                    "No se pudo eliminar la categoría.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_JBotonEliminar1ActionPerformed

    private void JComboBoxCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JComboBoxCategoriasActionPerformed
        String nombre = (String) JComboBoxCategorias.getSelectedItem();
        if (nombre == null || nombre.trim().isEmpty()) {
            JTextDescripcion.setText("");
            return;
        }

        CategoriaDao dao = new CategoriaDao();
        String descripcion = dao.descripcionPorNombre(nombre);

        if (descripcion != null) {
            JTextDescripcion.setText(descripcion);
        } else {
            JTextDescripcion.setText("");
        }
    }//GEN-LAST:event_JComboBoxCategoriasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Eliminar_Categoria().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BarraHorizontal;
    private javax.swing.JButton JBotonEliminar1;
    private javax.swing.JButton JBotonGuardar;
    private javax.swing.JButton JBotonSalir;
    private javax.swing.JComboBox<String> JComboBoxCategorias;
    private javax.swing.JTextArea JTextDescripcion;
    private javax.swing.JLabel TextCambiable;
    private javax.swing.JLabel TextVisualizacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
