package ui;

import core.Documento;
import data.CategoriaDao;
import data.DocumentoDao;
import javax.swing.JOptionPane;


public class Modificar_Documento extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Modificar_Documento.class.getName());
    private String idDocumento;
    
    
    /**
     * Creates new form Modificar_Documento
     */
    public Modificar_Documento(String idDocumento) {
        this.idDocumento = idDocumento;
        initComponents();
        cargarCombos();
        cargarDatosDocumento(idDocumento);
    }
    
    private void cargarCombos() {
        // Tipo de acceso
        JComboTipoAcceso.removeAllItems();
        JComboTipoAcceso.addItem("Seleccione tipo…");
        JComboTipoAcceso.addItem("PUBLICO");
        JComboTipoAcceso.addItem("INTERNO");
        JComboTipoAcceso.addItem("RESERVADO");

        // Disposición final
        JComboDisposicionFinal.removeAllItems();
        JComboDisposicionFinal.addItem("Seleccione disposición…");
        JComboDisposicionFinal.addItem("CONSERVAR");
        JComboDisposicionFinal.addItem("TRANSFERIR");
        JComboDisposicionFinal.addItem("ELIMINAR");

        // Categorías desde BD
        JComboCategorias.removeAllItems();
        JComboCategorias.addItem("Seleccione una categoría…");
        
        // Me lee la bases de datos y aparte los agrega al combobox
        try {
            for (String nombre : new CategoriaDao().listarNombres()) {
                JComboCategorias.addItem(nombre);
            }
        } catch (Exception ex) {
            System.err.println("No se pudieron cargar categorías: " + ex.getMessage());
        }
    }
    
    
    // Método para cargar los datos del documento desde la base de datos
    private void cargarDatosDocumento(String idDocumento) {
        try {
            Documento documento = new DocumentoDao().obtenerDocumentoPorId(idDocumento);
            if (documento != null) {
                // No editables (solo muestra)
                JLabelMunicipio.setText(documento.getMunicipio());
                JLabelDepartamento.setText(documento.getDepartamento());
                JLabelNombreOriginal.setText(documento.getFileName());
                JLabelFechaCreacion.setText(documento.getFechaCreacion());
                JLabelFechaActualizacion.setText(documento.getFechaActualizacion());
                TextNombreCreador.setText(documento.getUsuario_Demo()); // mapea a creador_nombre en la SQL
                TextCorreo.setText(documento.getCorreo_demo());         // mapea a creador_email en la SQL
                TextSize.setText(String.valueOf(documento.getFileSizeBytes()));

                // Editables
                JTextCodigo.setText(documento.getCodigo());
                JTextNombreDocumento.setText(documento.getNombre());
                AreaDescripcion.setText(documento.getDescripcion());
                JComboTipoAcceso.setSelectedItem(documento.getTipoAcceso());
                JComboDisposicionFinal.setSelectedItem(documento.getDisposicionFinal());

                // Seleccionar categoría por ID comparando contra idPorNombre(nombre)
                long idCatDoc = documento.getIdCategoria();
                for (int i = 1; i < JComboCategorias.getItemCount(); i++) { // desde 1 para saltar el placeholder
                    String nombreCat = (String) JComboCategorias.getItemAt(i);
                    long idCat = new data.CategoriaDao().idPorNombre(nombreCat);
                    if (idCat == idCatDoc) {
                        JComboCategorias.setSelectedIndex(i);
                        break;
                    }
                }
            }
        } catch (java.sql.SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al cargar el documento: " + e.getMessage(),
                                          "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TextVisualizacion = new javax.swing.JLabel();
        TextAcuerdo = new javax.swing.JLabel();
        BarraHorizontal = new javax.swing.JPanel();
        JTextNombreDocumento = new javax.swing.JTextField();
        JTextCodigo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        AreaDescripcion = new javax.swing.JTextArea();
        JBotonSalir = new javax.swing.JButton();
        JBotonModificar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        JComboDisposicionFinal = new javax.swing.JComboBox<>();
        JComboCategorias = new javax.swing.JComboBox<>();
        JComboTipoAcceso = new javax.swing.JComboBox<>();
        JPanelNameCreador = new javax.swing.JPanel();
        TextNombreCreador = new javax.swing.JLabel();
        JPanelNombreArchivoOriginal = new javax.swing.JPanel();
        JLabelNombreOriginal = new javax.swing.JLabel();
        JPanelFechaCreacion = new javax.swing.JPanel();
        JLabelFechaCreacion = new javax.swing.JLabel();
        JPanelMunicipio = new javax.swing.JPanel();
        JLabelMunicipio = new javax.swing.JLabel();
        JPanelCorreo = new javax.swing.JPanel();
        TextCorreo = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        JPanelSize = new javax.swing.JPanel();
        TextSize = new javax.swing.JLabel();
        JPanelUltimaActualizacion = new javax.swing.JPanel();
        JLabelFechaActualizacion = new javax.swing.JLabel();
        JPanelDepartamento = new javax.swing.JPanel();
        JLabelDepartamento = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 251, 248));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TextVisualizacion.setFont(new java.awt.Font("Inter", 1, 30)); // NOI18N
        TextVisualizacion.setText("Visualización Documento");
        jPanel1.add(TextVisualizacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        TextAcuerdo.setFont(new java.awt.Font("Inter", 1, 30)); // NOI18N
        TextAcuerdo.setForeground(new java.awt.Color(53, 91, 62));
        TextAcuerdo.setText("Del Acuerdo Municipal 001 de 2025");
        jPanel1.add(TextAcuerdo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        BarraHorizontal.setBackground(new java.awt.Color(219, 219, 219));

        javax.swing.GroupLayout BarraHorizontalLayout = new javax.swing.GroupLayout(BarraHorizontal);
        BarraHorizontal.setLayout(BarraHorizontalLayout);
        BarraHorizontalLayout.setHorizontalGroup(
            BarraHorizontalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        BarraHorizontalLayout.setVerticalGroup(
            BarraHorizontalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(BarraHorizontal, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 1000, 4));

        JTextNombreDocumento.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        JTextNombreDocumento.setText("Nombre del documento");
        JTextNombreDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTextNombreDocumentoActionPerformed(evt);
            }
        });
        jPanel1.add(JTextNombreDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 500, 40));

        JTextCodigo.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        JTextCodigo.setText("jTextField1");
        jPanel1.add(JTextCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 170, 230, 40));

        AreaDescripcion.setColumns(20);
        AreaDescripcion.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        AreaDescripcion.setRows(5);
        jScrollPane1.setViewportView(AreaDescripcion);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 1000, -1));

        JBotonSalir.setText("Salir");
        JBotonSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JBotonSalirMouseClicked(evt);
            }
        });
        jPanel1.add(JBotonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 640, 120, 40));

        JBotonModificar.setText("Modificar");
        JBotonModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JBotonModificarMouseClicked(evt);
            }
        });
        JBotonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBotonModificarActionPerformed(evt);
            }
        });
        jPanel1.add(JBotonModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 640, 120, 40));

        jLabel3.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jLabel3.setText("Archivo:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 230, 100, -1));

        jLabel4.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jLabel4.setText("Nombre de Documento:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 170, -1));

        jLabel6.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jLabel6.setText("Categorias:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 140, 100, -1));

        jLabel5.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jLabel5.setText("Codigo:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 140, 100, -1));

        jLabel7.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jLabel7.setText("Fecha de Disposicion Final:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 440, 240, -1));

        jLabel8.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jLabel8.setText("Departamento:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, 150, -1));

        jLabel9.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jLabel9.setText("Tipo de Acceso:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 230, 120, -1));

        jLabel10.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jLabel10.setText("Municipio:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 100, -1));

        jLabel11.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jLabel11.setText("Descripcion:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 100, -1));

        jLabel12.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jLabel12.setText("Fecha de creacion:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 180, -1));

        jLabel13.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jLabel13.setText("Tamaño en MB:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 540, 180, -1));

        jLabel14.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jLabel14.setText("Fecha de Ultima Actualizacion:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 440, 230, -1));

        jLabel15.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jLabel15.setText("Nombre de Creador:");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 530, 180, -1));

        JComboDisposicionFinal.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        JComboDisposicionFinal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(JComboDisposicionFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 470, 320, 40));

        JComboCategorias.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        JComboCategorias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(JComboCategorias, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 170, 210, 40));

        JComboTipoAcceso.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        JComboTipoAcceso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(JComboTipoAcceso, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 260, 170, 40));

        TextNombreCreador.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        TextNombreCreador.setText("Nombre del creador");

        javax.swing.GroupLayout JPanelNameCreadorLayout = new javax.swing.GroupLayout(JPanelNameCreador);
        JPanelNameCreador.setLayout(JPanelNameCreadorLayout);
        JPanelNameCreadorLayout.setHorizontalGroup(
            JPanelNameCreadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelNameCreadorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TextNombreCreador, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        JPanelNameCreadorLayout.setVerticalGroup(
            JPanelNameCreadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelNameCreadorLayout.createSequentialGroup()
                .addComponent(TextNombreCreador, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(JPanelNameCreador, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 570, 310, 40));

        JLabelNombreOriginal.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        JLabelNombreOriginal.setText("Nombre del archivo");

        javax.swing.GroupLayout JPanelNombreArchivoOriginalLayout = new javax.swing.GroupLayout(JPanelNombreArchivoOriginal);
        JPanelNombreArchivoOriginal.setLayout(JPanelNombreArchivoOriginalLayout);
        JPanelNombreArchivoOriginalLayout.setHorizontalGroup(
            JPanelNombreArchivoOriginalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelNombreArchivoOriginalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLabelNombreOriginal, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                .addContainerGap())
        );
        JPanelNombreArchivoOriginalLayout.setVerticalGroup(
            JPanelNombreArchivoOriginalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JLabelNombreOriginal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(JPanelNombreArchivoOriginal, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 260, 240, 40));

        JLabelFechaCreacion.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        JLabelFechaCreacion.setText("Fecha de creacion");

        javax.swing.GroupLayout JPanelFechaCreacionLayout = new javax.swing.GroupLayout(JPanelFechaCreacion);
        JPanelFechaCreacion.setLayout(JPanelFechaCreacionLayout);
        JPanelFechaCreacionLayout.setHorizontalGroup(
            JPanelFechaCreacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelFechaCreacionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLabelFechaCreacion, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        JPanelFechaCreacionLayout.setVerticalGroup(
            JPanelFechaCreacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelFechaCreacionLayout.createSequentialGroup()
                .addComponent(JLabelFechaCreacion, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(JPanelFechaCreacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, 310, 40));

        JLabelMunicipio.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        JLabelMunicipio.setText("Municipio");

        javax.swing.GroupLayout JPanelMunicipioLayout = new javax.swing.GroupLayout(JPanelMunicipio);
        JPanelMunicipio.setLayout(JPanelMunicipioLayout);
        JPanelMunicipioLayout.setHorizontalGroup(
            JPanelMunicipioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelMunicipioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLabelMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        JPanelMunicipioLayout.setVerticalGroup(
            JPanelMunicipioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelMunicipioLayout.createSequentialGroup()
                .addComponent(JLabelMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(JPanelMunicipio, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 240, 40));

        TextCorreo.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        TextCorreo.setText("Correo del creador");

        javax.swing.GroupLayout JPanelCorreoLayout = new javax.swing.GroupLayout(JPanelCorreo);
        JPanelCorreo.setLayout(JPanelCorreoLayout);
        JPanelCorreoLayout.setHorizontalGroup(
            JPanelCorreoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelCorreoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TextCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        JPanelCorreoLayout.setVerticalGroup(
            JPanelCorreoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelCorreoLayout.createSequentialGroup()
                .addComponent(TextCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(JPanelCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 570, 310, 40));

        jLabel21.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jLabel21.setText("Correo del Creador:");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 540, 180, -1));

        TextSize.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        TextSize.setText("Tamaño del archivo");

        javax.swing.GroupLayout JPanelSizeLayout = new javax.swing.GroupLayout(JPanelSize);
        JPanelSize.setLayout(JPanelSizeLayout);
        JPanelSizeLayout.setHorizontalGroup(
            JPanelSizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelSizeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TextSize, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        JPanelSizeLayout.setVerticalGroup(
            JPanelSizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelSizeLayout.createSequentialGroup()
                .addComponent(TextSize, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(JPanelSize, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 570, 320, -1));

        JLabelFechaActualizacion.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        JLabelFechaActualizacion.setText("Fecha de ultima actualizacion");

        javax.swing.GroupLayout JPanelUltimaActualizacionLayout = new javax.swing.GroupLayout(JPanelUltimaActualizacion);
        JPanelUltimaActualizacion.setLayout(JPanelUltimaActualizacionLayout);
        JPanelUltimaActualizacionLayout.setHorizontalGroup(
            JPanelUltimaActualizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelUltimaActualizacionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLabelFechaActualizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        JPanelUltimaActualizacionLayout.setVerticalGroup(
            JPanelUltimaActualizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelUltimaActualizacionLayout.createSequentialGroup()
                .addComponent(JLabelFechaActualizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(JPanelUltimaActualizacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 470, 310, 40));

        JLabelDepartamento.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        JLabelDepartamento.setText("Departamento");

        javax.swing.GroupLayout JPanelDepartamentoLayout = new javax.swing.GroupLayout(JPanelDepartamento);
        JPanelDepartamento.setLayout(JPanelDepartamentoLayout);
        JPanelDepartamentoLayout.setHorizontalGroup(
            JPanelDepartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelDepartamentoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLabelDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        JPanelDepartamentoLayout.setVerticalGroup(
            JPanelDepartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelDepartamentoLayout.createSequentialGroup()
                .addComponent(JLabelDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(JPanelDepartamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1070, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 704, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBotonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBotonModificarActionPerformed
        try {
            // Validaciones sencillas
            if (JTextNombreDocumento.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "El nombre es obligatorio.", "Validación", JOptionPane.WARNING_MESSAGE);
                return;
            }
            if (JComboCategorias.getSelectedIndex() == 0) {
                JOptionPane.showMessageDialog(this, "Seleccione una categoría.", "Validación", JOptionPane.WARNING_MESSAGE);
                return;
            }
            if (JComboTipoAcceso.getSelectedIndex() == 0) {
                JOptionPane.showMessageDialog(this, "Seleccione un tipo de acceso.", "Validación", JOptionPane.WARNING_MESSAGE);
                return;
            }
            if (JComboDisposicionFinal.getSelectedIndex() == 0) {
                JOptionPane.showMessageDialog(this, "Seleccione la disposición final.", "Validación", JOptionPane.WARNING_MESSAGE);
                return;
            }

            // Construir el Documento con los campos editables
            core.Documento d = new core.Documento();
            d.setIdDocumento(Long.parseLong(this.idDocumento)); // viene del constructor
            d.setNombre(JTextNombreDocumento.getText().trim());
            d.setCodigo(JTextCodigo.getText().trim());
            d.setDescripcion(AreaDescripcion.getText().trim());
            d.setTipoAcceso((String) JComboTipoAcceso.getSelectedItem());
            d.setDisposicionFinal((String) JComboDisposicionFinal.getSelectedItem());

            // ID de categoría a partir del nombre seleccionado
            String nombreCategoria = (String) JComboCategorias.getSelectedItem();
            long idCategoria = new data.CategoriaDao().idPorNombre(nombreCategoria);
            d.setIdCategoria(idCategoria);

            // Mantener el nombre de archivo que se muestra (si no se cambia en esta pantalla)
            d.setFileName(JLabelNombreOriginal.getText().trim());

            boolean ok = new data.DocumentoDao().actualizarDocumento(d);

            if (ok) {
                JOptionPane.showMessageDialog(this, "Documento actualizado correctamente.");
                this.dispose();
                Gestor_De_Documentos g = new Gestor_De_Documentos("", 0L);
                g.setLocationRelativeTo(null);
                g.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "No se actualizó ninguna fila.", "Aviso", JOptionPane.INFORMATION_MESSAGE);
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error al actualizar: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_JBotonModificarActionPerformed

    private void JBotonModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBotonModificarMouseClicked

    }//GEN-LAST:event_JBotonModificarMouseClicked

    private void JTextNombreDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTextNombreDocumentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTextNombreDocumentoActionPerformed

    private void JBotonSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBotonSalirMouseClicked
        this.dispose();

        Gestor_De_Documentos ventanaGestor = new Gestor_De_Documentos("", 0L);
        ventanaGestor.setLocationRelativeTo(null);
        ventanaGestor.setVisible(true);
    }//GEN-LAST:event_JBotonSalirMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Modificar_Documento("1").setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AreaDescripcion;
    private javax.swing.JPanel BarraHorizontal;
    private javax.swing.JButton JBotonModificar;
    private javax.swing.JButton JBotonSalir;
    private javax.swing.JComboBox<String> JComboCategorias;
    private javax.swing.JComboBox<String> JComboDisposicionFinal;
    private javax.swing.JComboBox<String> JComboTipoAcceso;
    private javax.swing.JLabel JLabelDepartamento;
    private javax.swing.JLabel JLabelFechaActualizacion;
    private javax.swing.JLabel JLabelFechaCreacion;
    private javax.swing.JLabel JLabelMunicipio;
    private javax.swing.JLabel JLabelNombreOriginal;
    private javax.swing.JPanel JPanelCorreo;
    private javax.swing.JPanel JPanelDepartamento;
    private javax.swing.JPanel JPanelFechaCreacion;
    private javax.swing.JPanel JPanelMunicipio;
    private javax.swing.JPanel JPanelNameCreador;
    private javax.swing.JPanel JPanelNombreArchivoOriginal;
    private javax.swing.JPanel JPanelSize;
    private javax.swing.JPanel JPanelUltimaActualizacion;
    private javax.swing.JTextField JTextCodigo;
    private javax.swing.JTextField JTextNombreDocumento;
    private javax.swing.JLabel TextAcuerdo;
    private javax.swing.JLabel TextCorreo;
    private javax.swing.JLabel TextNombreCreador;
    private javax.swing.JLabel TextSize;
    private javax.swing.JLabel TextVisualizacion;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
