/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import java.awt.Color;
import javax.swing.JOptionPane;
import logica.CategoriaDao;

/**
 *
 * @author Juan Pablo
 */
public class Nueva_Categoria extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Nueva_Categoria.class.getName());
    
    private static final String PLACEHOLDER_NOMBRE = "Nombre de la categoría";
    private static final String PLACEHOLDER_DESCRIPCION = "Descripción de la categoría";


    /**
     * Creates new form Nueva_Categoria
     */
    public Nueva_Categoria() {
        initComponents();
        
            // Placeholders iniciales
        JTextNombreCategoria.setText(PLACEHOLDER_NOMBRE);
        JTextNombreCategoria.setForeground(Color.GRAY);

        JTextDescripcionArea.setText(PLACEHOLDER_DESCRIPCION);
        JTextDescripcionArea.setForeground(Color.GRAY);
        
    }
    
    // ===== Helpers de placeholders =====

    private void limpiarCampoTexto(javax.swing.JTextField campo, String placeholder) {
        if (campo.getText().equals(placeholder)) {
            campo.setText("");
            campo.setForeground(Color.BLACK);
        }
    }

    private void restaurarCampoTexto(javax.swing.JTextField campo, String placeholder) {
        if (campo.getText().trim().isEmpty()) {
            campo.setText(placeholder);
            campo.setForeground(Color.GRAY);
        }
    }

    private void limpiarAreaTexto(javax.swing.JTextArea area, String placeholder) {
        if (area.getText().equals(placeholder)) {
            area.setText("");
            area.setForeground(Color.BLACK);
        }
    }

    private void restaurarAreaTexto(javax.swing.JTextArea area, String placeholder) {
        if (area.getText().trim().isEmpty()) {
            area.setText(placeholder);
            area.setForeground(Color.GRAY);
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TextVisualizacion = new javax.swing.JLabel();
        TextoCambiable = new javax.swing.JLabel();
        JBotonSalir = new javax.swing.JButton();
        JBotonGuardar = new javax.swing.JButton();
        BarraHorizontal = new javax.swing.JPanel();
        JTextNombreCategoria = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTextDescripcionArea = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 251, 248));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TextVisualizacion.setFont(new java.awt.Font("Inter", 1, 30)); // NOI18N
        TextVisualizacion.setText("Crear Nueva");
        jPanel1.add(TextVisualizacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        TextoCambiable.setFont(new java.awt.Font("Inter", 1, 30)); // NOI18N
        TextoCambiable.setForeground(new java.awt.Color(53, 91, 62));
        TextoCambiable.setText("Categoria");
        jPanel1.add(TextoCambiable, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        JBotonSalir.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        JBotonSalir.setText("Salir");
        JBotonSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JBotonSalirMouseClicked(evt);
            }
        });
        JBotonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBotonSalirActionPerformed(evt);
            }
        });
        jPanel1.add(JBotonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 370, 110, 50));

        JBotonGuardar.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        JBotonGuardar.setText("Guardar");
        JBotonGuardar.setActionCommand("GUARDAR");
        JBotonGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JBotonGuardarMouseClicked(evt);
            }
        });
        JBotonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBotonGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(JBotonGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 370, 110, 50));

        BarraHorizontal.setBackground(new java.awt.Color(219, 219, 219));

        javax.swing.GroupLayout BarraHorizontalLayout = new javax.swing.GroupLayout(BarraHorizontal);
        BarraHorizontal.setLayout(BarraHorizontalLayout);
        BarraHorizontalLayout.setHorizontalGroup(
            BarraHorizontalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        BarraHorizontalLayout.setVerticalGroup(
            BarraHorizontalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(BarraHorizontal, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 580, 10));

        JTextNombreCategoria.setText("jTextField1");
        JTextNombreCategoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JTextNombreCategoriaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JTextNombreCategoriaMousePressed(evt);
            }
        });
        jPanel1.add(JTextNombreCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 580, 40));

        JTextDescripcionArea.setColumns(20);
        JTextDescripcionArea.setRows(5);
        JTextDescripcionArea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JTextDescripcionAreaMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(JTextDescripcionArea);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 580, -1));

        jLabel1.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jLabel1.setText("Descripcion Categoria:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 180, -1));

        jLabel2.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jLabel2.setText("Nombre Categoria:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 180, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 641, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBotonSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBotonSalirMouseClicked
        this.dispose();

        Gestor_De_Documentos ventanaGestorDocumentos = new Gestor_De_Documentos("", 0L);
        ventanaGestorDocumentos.setLocationRelativeTo(null);
        ventanaGestorDocumentos.setVisible(true);
    }//GEN-LAST:event_JBotonSalirMouseClicked

    private void JBotonGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBotonGuardarMouseClicked
        String nombre = JTextNombreCategoria.getText().trim();
        String descripcion = JTextDescripcionArea.getText().trim();

        // Validar nombre obligatorio
        if (nombre.isEmpty()) {
            JOptionPane.showMessageDialog(
                    this,
                    "El nombre de la categoría es obligatorio.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );
            return;
        }

        // Llamar al DAO
        CategoriaDao dao = new CategoriaDao();
        boolean creada = dao.crearCategoria(nombre, descripcion);

        if (creada) {
            JOptionPane.showMessageDialog(
                    this,
                    "Categoría creada correctamente.",
                    "Éxito",
                    JOptionPane.INFORMATION_MESSAGE
            );

            // Cerrar esta ventana y volver al gestor (si así lo quieres)
            this.dispose();
            Gesto_De_Usuarios ventanaGestorDeUsuario = new Gesto_De_Usuarios();
            ventanaGestorDeUsuario.setLocationRelativeTo(null);
            ventanaGestorDeUsuario.setVisible(true);

        } else {
            JOptionPane.showMessageDialog(
                    this,
                    "Ya existe una categoría con ese nombre\n"
                  + "o no se pudo crear la categoría.",
                    "Aviso",
                    JOptionPane.WARNING_MESSAGE
            );
        }
    }//GEN-LAST:event_JBotonGuardarMouseClicked

    private void JBotonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBotonGuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBotonGuardarActionPerformed

    private void JBotonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBotonSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBotonSalirActionPerformed

    private void JTextNombreCategoriaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTextNombreCategoriaMousePressed
        // Limpiar el campo nombre si está el placeholder
        limpiarCampoTexto(JTextNombreCategoria, PLACEHOLDER_NOMBRE);

        // Restaurar descripción si quedó vacía
        restaurarAreaTexto(JTextDescripcionArea, PLACEHOLDER_DESCRIPCION);
    }//GEN-LAST:event_JTextNombreCategoriaMousePressed

    private void JTextNombreCategoriaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTextNombreCategoriaMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_JTextNombreCategoriaMouseExited

    private void JTextDescripcionAreaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTextDescripcionAreaMousePressed
        // Limpiar el área de descripción si está el placeholder
        limpiarAreaTexto(JTextDescripcionArea, PLACEHOLDER_DESCRIPCION);

        // Restaurar nombre si quedó vacío
        restaurarCampoTexto(JTextNombreCategoria, PLACEHOLDER_NOMBRE);
    }//GEN-LAST:event_JTextDescripcionAreaMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Nueva_Categoria().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BarraHorizontal;
    private javax.swing.JButton JBotonGuardar;
    private javax.swing.JButton JBotonSalir;
    private javax.swing.JTextArea JTextDescripcionArea;
    private javax.swing.JTextField JTextNombreCategoria;
    private javax.swing.JLabel TextVisualizacion;
    private javax.swing.JLabel TextoCambiable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
