package ui;

import persistencia.Documento;
import logica.CategoriaDao;
import logica.DocumentoDao;
import java.sql.SQLException;




public class Ver_Documento extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Ver_Documento.class.getName());
    private String idDocumento;
    
    
    /**
     * Creates new form Modificar_Documento
     */
    public Ver_Documento(String idDocumento) throws SQLException {
        this.idDocumento = idDocumento;
        initComponents();

        Documento documento = new Documento();
        documento = new DocumentoDao().obtenerDocumentoPorId(idDocumento);
        
        long sizeBytes = documento.getFileSizeBytes();
        double sizeMB = sizeBytes / 1_000_000.0; 
        
        JLabelNombre.setText(documento.getNombre());
        JLabelCategoria.setText(new CategoriaDao().nombrePorId(documento.getIdCategoria()));
        JLabelCodigo.setText(documento.getCodigo());
        JLabelMunicipio.setText(documento.getMunicipio());
        JLabelDepartamento.setText(documento.getDepartamento());
        JLabelTipoAcceso.setText(documento.getTipoAcceso());
        JLabelNombreOriginal.setText(documento.getFileName());
        JLabelDescripcion.setText(documento.getDescripcion());
        JLabelFechaCreacion.setText(documento.getFechaCreacion());
        JLabelFechaActualizacion.setText(documento.getFechaActualizacion());
        JLabelDisposicion.setText(documento.getDisposicionFinal());
        JLabelNombreCreador.setText(documento.getUsuario_Demo());
        JLabelCorreoCreador.setText(documento.getCorreo_demo());
        JLabelSize.setText(String.format("%.2f MB", sizeMB));
        
        TextCambiable.setText(documento.getNombre());
        
    }
    

    
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TextVisualizacion = new javax.swing.JLabel();
        TextCambiable = new javax.swing.JLabel();
        BarraHorizontal = new javax.swing.JPanel();
        JBotonSalir = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        JPanelNameCreador = new javax.swing.JPanel();
        JLabelNombreCreador = new javax.swing.JLabel();
        JPanelNombreArchivoOriginal = new javax.swing.JPanel();
        JLabelNombreOriginal = new javax.swing.JLabel();
        JPanelFechaCreacion = new javax.swing.JPanel();
        JLabelFechaCreacion = new javax.swing.JLabel();
        JPanelMunicipio = new javax.swing.JPanel();
        JLabelMunicipio = new javax.swing.JLabel();
        JPanelCorreo = new javax.swing.JPanel();
        JLabelCorreoCreador = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        JPanelSize = new javax.swing.JPanel();
        JLabelSize = new javax.swing.JLabel();
        JPanelUltimaActualizacion = new javax.swing.JPanel();
        JLabelFechaActualizacion = new javax.swing.JLabel();
        JPanelDepartamento = new javax.swing.JPanel();
        JLabelDepartamento = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        JLabelDescripcion = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        JLabelNombre = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        JLabelCodigo = new javax.swing.JLabel();
        JPanelMunicipio1 = new javax.swing.JPanel();
        JLabelTipoAcceso = new javax.swing.JLabel();
        JPanelMunicipio2 = new javax.swing.JPanel();
        JLabelCategoria = new javax.swing.JLabel();
        JPanelMunicipio3 = new javax.swing.JPanel();
        JLabelDisposicion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 251, 248));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TextVisualizacion.setFont(new java.awt.Font("Inter", 1, 30)); // NOI18N
        TextVisualizacion.setText("Visualización Documento");
        jPanel1.add(TextVisualizacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        TextCambiable.setFont(new java.awt.Font("Inter", 1, 30)); // NOI18N
        TextCambiable.setForeground(new java.awt.Color(53, 91, 62));
        TextCambiable.setText("Cositas cositas");
        jPanel1.add(TextCambiable, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        BarraHorizontal.setBackground(new java.awt.Color(219, 219, 219));

        javax.swing.GroupLayout BarraHorizontalLayout = new javax.swing.GroupLayout(BarraHorizontal);
        BarraHorizontal.setLayout(BarraHorizontalLayout);
        BarraHorizontalLayout.setHorizontalGroup(
            BarraHorizontalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        BarraHorizontalLayout.setVerticalGroup(
            BarraHorizontalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(BarraHorizontal, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 1000, 4));

        JBotonSalir.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        JBotonSalir.setText("Salir");
        JBotonSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JBotonSalirMouseClicked(evt);
            }
        });
        jPanel1.add(JBotonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 640, 120, 40));

        jLabel3.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jLabel3.setText("Archivo:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 230, 100, -1));

        jLabel4.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jLabel4.setText("Nombre de Documento:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 170, -1));

        jLabel6.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jLabel6.setText("Categorias:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 140, 100, -1));

        jLabel5.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jLabel5.setText("Codigo:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 140, 100, -1));

        jLabel7.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jLabel7.setText("Fecha de Disposicion Final:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 440, 240, -1));

        jLabel8.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jLabel8.setText("Departamento:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, 150, -1));

        jLabel9.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jLabel9.setText("Tipo de Acceso:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 230, 120, -1));

        jLabel10.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jLabel10.setText("Municipio:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 100, -1));

        jLabel11.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jLabel11.setText("Descripcion:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 100, -1));

        jLabel12.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jLabel12.setText("Fecha de creacion:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 180, -1));

        jLabel13.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jLabel13.setText("Tamaño en MB:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 540, 180, -1));

        jLabel14.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jLabel14.setText("Fecha de Ultima Actualizacion:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 440, 230, -1));

        jLabel15.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jLabel15.setText("Nombre de Creador:");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 540, 180, -1));

        JLabelNombreCreador.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        JLabelNombreCreador.setText("Nombre del creador");

        javax.swing.GroupLayout JPanelNameCreadorLayout = new javax.swing.GroupLayout(JPanelNameCreador);
        JPanelNameCreador.setLayout(JPanelNameCreadorLayout);
        JPanelNameCreadorLayout.setHorizontalGroup(
            JPanelNameCreadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelNameCreadorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLabelNombreCreador, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        JPanelNameCreadorLayout.setVerticalGroup(
            JPanelNameCreadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelNameCreadorLayout.createSequentialGroup()
                .addComponent(JLabelNombreCreador, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(JPanelNameCreador, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 570, 310, 40));

        JLabelNombreOriginal.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        JLabelNombreOriginal.setText("Nombre del archivo");

        javax.swing.GroupLayout JPanelNombreArchivoOriginalLayout = new javax.swing.GroupLayout(JPanelNombreArchivoOriginal);
        JPanelNombreArchivoOriginal.setLayout(JPanelNombreArchivoOriginalLayout);
        JPanelNombreArchivoOriginalLayout.setHorizontalGroup(
            JPanelNombreArchivoOriginalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelNombreArchivoOriginalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLabelNombreOriginal, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                .addContainerGap())
        );
        JPanelNombreArchivoOriginalLayout.setVerticalGroup(
            JPanelNombreArchivoOriginalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JLabelNombreOriginal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(JPanelNombreArchivoOriginal, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 260, 240, 40));

        JLabelFechaCreacion.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        JLabelFechaCreacion.setText("Fecha de creacion");

        javax.swing.GroupLayout JPanelFechaCreacionLayout = new javax.swing.GroupLayout(JPanelFechaCreacion);
        JPanelFechaCreacion.setLayout(JPanelFechaCreacionLayout);
        JPanelFechaCreacionLayout.setHorizontalGroup(
            JPanelFechaCreacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelFechaCreacionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLabelFechaCreacion, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        JPanelFechaCreacionLayout.setVerticalGroup(
            JPanelFechaCreacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelFechaCreacionLayout.createSequentialGroup()
                .addComponent(JLabelFechaCreacion, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(JPanelFechaCreacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, 310, 40));

        JLabelMunicipio.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        JLabelMunicipio.setText("Municipio");

        javax.swing.GroupLayout JPanelMunicipioLayout = new javax.swing.GroupLayout(JPanelMunicipio);
        JPanelMunicipio.setLayout(JPanelMunicipioLayout);
        JPanelMunicipioLayout.setHorizontalGroup(
            JPanelMunicipioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelMunicipioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLabelMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        JPanelMunicipioLayout.setVerticalGroup(
            JPanelMunicipioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelMunicipioLayout.createSequentialGroup()
                .addComponent(JLabelMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(JPanelMunicipio, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 240, 40));

        JLabelCorreoCreador.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        JLabelCorreoCreador.setText("Correo del creador");

        javax.swing.GroupLayout JPanelCorreoLayout = new javax.swing.GroupLayout(JPanelCorreo);
        JPanelCorreo.setLayout(JPanelCorreoLayout);
        JPanelCorreoLayout.setHorizontalGroup(
            JPanelCorreoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelCorreoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLabelCorreoCreador, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        JPanelCorreoLayout.setVerticalGroup(
            JPanelCorreoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelCorreoLayout.createSequentialGroup()
                .addComponent(JLabelCorreoCreador, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(JPanelCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 570, 310, 40));

        jLabel21.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jLabel21.setText("Correo del Creador:");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 540, 180, -1));

        JLabelSize.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        JLabelSize.setText("Tamaño del archivo");

        javax.swing.GroupLayout JPanelSizeLayout = new javax.swing.GroupLayout(JPanelSize);
        JPanelSize.setLayout(JPanelSizeLayout);
        JPanelSizeLayout.setHorizontalGroup(
            JPanelSizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelSizeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLabelSize, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        JPanelSizeLayout.setVerticalGroup(
            JPanelSizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelSizeLayout.createSequentialGroup()
                .addComponent(JLabelSize, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(JPanelSize, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 570, 320, -1));

        JLabelFechaActualizacion.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        JLabelFechaActualizacion.setText("Fecha de ultima actualizacion");

        javax.swing.GroupLayout JPanelUltimaActualizacionLayout = new javax.swing.GroupLayout(JPanelUltimaActualizacion);
        JPanelUltimaActualizacion.setLayout(JPanelUltimaActualizacionLayout);
        JPanelUltimaActualizacionLayout.setHorizontalGroup(
            JPanelUltimaActualizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelUltimaActualizacionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLabelFechaActualizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        JPanelUltimaActualizacionLayout.setVerticalGroup(
            JPanelUltimaActualizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelUltimaActualizacionLayout.createSequentialGroup()
                .addComponent(JLabelFechaActualizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(JPanelUltimaActualizacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 470, 310, 40));

        JLabelDepartamento.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        JLabelDepartamento.setText("Departamento");

        javax.swing.GroupLayout JPanelDepartamentoLayout = new javax.swing.GroupLayout(JPanelDepartamento);
        JPanelDepartamento.setLayout(JPanelDepartamentoLayout);
        JPanelDepartamentoLayout.setHorizontalGroup(
            JPanelDepartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelDepartamentoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLabelDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        JPanelDepartamentoLayout.setVerticalGroup(
            JPanelDepartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelDepartamentoLayout.createSequentialGroup()
                .addComponent(JLabelDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(JPanelDepartamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, -1, -1));

        JLabelDescripcion.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        JLabelDescripcion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        JLabelDescripcion.setText("Descripcion del Documento");
        JLabelDescripcion.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLabelDescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, 988, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLabelDescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 1000, 80));

        JLabelNombre.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        JLabelNombre.setText("Nombre Documento");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLabelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JLabelNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 510, 37));

        JLabelCodigo.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        JLabelCodigo.setText("Codigo del Documento");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLabelCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JLabelCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 170, 240, 37));

        JLabelTipoAcceso.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        JLabelTipoAcceso.setText("Municipio");

        javax.swing.GroupLayout JPanelMunicipio1Layout = new javax.swing.GroupLayout(JPanelMunicipio1);
        JPanelMunicipio1.setLayout(JPanelMunicipio1Layout);
        JPanelMunicipio1Layout.setHorizontalGroup(
            JPanelMunicipio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelMunicipio1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLabelTipoAcceso, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        JPanelMunicipio1Layout.setVerticalGroup(
            JPanelMunicipio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelMunicipio1Layout.createSequentialGroup()
                .addComponent(JLabelTipoAcceso, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(JPanelMunicipio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 260, 190, -1));

        JLabelCategoria.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        JLabelCategoria.setText("Municipio");

        javax.swing.GroupLayout JPanelMunicipio2Layout = new javax.swing.GroupLayout(JPanelMunicipio2);
        JPanelMunicipio2.setLayout(JPanelMunicipio2Layout);
        JPanelMunicipio2Layout.setHorizontalGroup(
            JPanelMunicipio2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelMunicipio2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLabelCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        JPanelMunicipio2Layout.setVerticalGroup(
            JPanelMunicipio2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelMunicipio2Layout.createSequentialGroup()
                .addComponent(JLabelCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(JPanelMunicipio2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 170, 210, -1));

        JLabelDisposicion.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        JLabelDisposicion.setText("Disposicion Final");

        javax.swing.GroupLayout JPanelMunicipio3Layout = new javax.swing.GroupLayout(JPanelMunicipio3);
        JPanelMunicipio3.setLayout(JPanelMunicipio3Layout);
        JPanelMunicipio3Layout.setHorizontalGroup(
            JPanelMunicipio3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelMunicipio3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLabelDisposicion, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        JPanelMunicipio3Layout.setVerticalGroup(
            JPanelMunicipio3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelMunicipio3Layout.createSequentialGroup()
                .addComponent(JLabelDisposicion, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(JPanelMunicipio3, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 470, 320, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1070, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 704, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBotonSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBotonSalirMouseClicked
        this.dispose();

        Gestor_De_Documentos ventanaGestor = new Gestor_De_Documentos("", 0L);
        ventanaGestor.setLocationRelativeTo(null);
        ventanaGestor.setVisible(true);
    }//GEN-LAST:event_JBotonSalirMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new Ver_Documento("1").setVisible(true);
            } catch (SQLException ex) {
                System.getLogger(Ver_Documento.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BarraHorizontal;
    private javax.swing.JButton JBotonSalir;
    private javax.swing.JLabel JLabelCategoria;
    private javax.swing.JLabel JLabelCodigo;
    private javax.swing.JLabel JLabelCorreoCreador;
    private javax.swing.JLabel JLabelDepartamento;
    private javax.swing.JLabel JLabelDescripcion;
    private javax.swing.JLabel JLabelDisposicion;
    private javax.swing.JLabel JLabelFechaActualizacion;
    private javax.swing.JLabel JLabelFechaCreacion;
    private javax.swing.JLabel JLabelMunicipio;
    private javax.swing.JLabel JLabelNombre;
    private javax.swing.JLabel JLabelNombreCreador;
    private javax.swing.JLabel JLabelNombreOriginal;
    private javax.swing.JLabel JLabelSize;
    private javax.swing.JLabel JLabelTipoAcceso;
    private javax.swing.JPanel JPanelCorreo;
    private javax.swing.JPanel JPanelDepartamento;
    private javax.swing.JPanel JPanelFechaCreacion;
    private javax.swing.JPanel JPanelMunicipio;
    private javax.swing.JPanel JPanelMunicipio1;
    private javax.swing.JPanel JPanelMunicipio2;
    private javax.swing.JPanel JPanelMunicipio3;
    private javax.swing.JPanel JPanelNameCreador;
    private javax.swing.JPanel JPanelNombreArchivoOriginal;
    private javax.swing.JPanel JPanelSize;
    private javax.swing.JPanel JPanelUltimaActualizacion;
    private javax.swing.JLabel TextCambiable;
    private javax.swing.JLabel TextVisualizacion;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
